### ISSUE TITLE
部分接口失效

### ISSUE THREAD

**Issue by guoruibiao** [Alexzhuangyao/smsBang#1]
实测了下发现有几个接口是失效状态，我个人觉得，这个短信轰炸机很赞。
如果真要进行轰炸，一般一个平台1~5分钟内不会接受同一个手机号的发送请求，因此sleep那块也就不是很适用了。后续如果要维护很多这样的接口，写很多个类可能也不划算，看这些接口基本上大同小异，无非是header和post数据的不同，能否通过配置文件的形式将这些不同点单独剖出来，然后通用的get_response和run方法单独隔离出来，通过工厂模式来创建不同接口的轰炸实例，这样估计以后的维护代价会小很多。

**Comment by Alexzhuangyao** [comment]
感谢你的建议，这个demo其实有很大改进空间，对你提出的问题，是已知的，后期要加代理池，header池，将直接区分get和post方法。“一般一个平台1~5分钟内不会接受同一个手机号的发送请求”，这种平台其实挺少的，一般都做在前端限制60秒。

**Comment by Jeason-T** [comment]
为什么收不到短信呢，是不是已经失效了
